repos:
-   repo: local
    hooks:
    -   id: docker-ruff
        name: ruff
        description: ruff
        entry: registry.atb-it.ru/linters/python-lints/ruff:latest
        args: ["ruff", "--config=/pyproject.toml"]
        language: docker_image
        files: \.(py)$
